#include <bits/stdc++.h>
using namespace std;

class ChessMetric
{
    int N;
    vector<pair<int, int>> jumps;
    int xStart, yStart;
    long long memo[101][101][51];

    bool isValid(int x, int y) {
        return x >= 0 && x < N && y >= 0 && y < N;
    }

    long long cntWays(int x, int y, int steps) {
        if(steps == 0)
            return (x == xStart && y == yStart) ? 1 : 0ll;
        if(not isValid(x, y))
            return 0ll;
        auto &ret = memo[x][y][steps];
        if(ret == -1ll)
            ret = accumulate( jumps.begin()
                            , jumps.end()
                            , 0ll
                            , [=](long long acc, pair<int, int> jump) {
                                  return acc + cntWays(x + jump.first, y + jump.second, steps-1);
                              }
                            );
        return ret;
    }


public:
    long long howMany(int size, vector <int> start, vector <int> end, int numMoves)
    {
        N = size;
        xStart = start[0];
        yStart = start[1];
        memset(memo, -1ll, sizeof(memo));

        for(int r = -2; r <= 2; r++) {
            for(int c = -2; c <= 2; c++) {
                if(abs(r) + abs(c) == 3)            // Consider L move
                    jumps.push_back({r, c});
                else if(abs(r) == 1 && abs(c) == 1) // Consider corner element
                    jumps.push_back({r, c});
                else if(abs(r) + abs(c) == 1)       // Consider sideways element
                    jumps.push_back({r, c});
            }
        }
        return cntWays(end[0], end[1], numMoves);
    }
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, vector <int> p1, vector <int> p2, int p3, bool hasAnswer, long long p4) {
	cout << "Test " << testNum << ": [" << p0 << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}" << "," << p3;
	cout << "]" << endl;
	ChessMetric *obj;
	long long answer;
	obj = new ChessMetric();
	clock_t startTime = clock();
	answer = obj->howMany(p0, p1, p2, p3);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p4 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p4;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	vector <int> p1;
	vector <int> p2;
	int p3;
	long long p4;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 3;
	p1 = {0,0};
	p2 = {1,0};
	p3 = 1;
	p4 = 1ll;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 3;
	p1 = {0,0};
	p2 = {1,2};
	p3 = 1;
	p4 = 1ll;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 3;
	p1 = {0,0};
	p2 = {2,2};
	p3 = 1;
	p4 = 0ll;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 3;
	p1 = {0,0};
	p2 = {0,0};
	p3 = 2;
	p4 = 5ll;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 4 -----
	disabled = false;
	p0 = 100;
	p1 = {0,0};
	p2 = {0,99};
	p3 = 50;
	p4 = 243097320072600ll;
	all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Suppose you had an n by n chess board and a super piece called a kingknight.  Using only one move the kingknight denoted 'K' below can reach any of the spaces denoted 'X' or 'L' below:
//    .......
//    ..L.L..
//    .LXXXL.
//    ..XKX..
//    .LXXXL.
//    ..L.L..
//    .......
// 
// In other words, the kingknight can move either one space in any direction (vertical, horizontal or diagonally) or can make an 'L' shaped move.  An 'L' shaped move involves moving 2 spaces horizontally then 1 space vertically or 2 spaces vertically then 1 space horizontally.  In the drawing above, the 'L' shaped moves are marked with 'L's whereas the one space moves are marked with 'X's.  In addition, a kingknight may never jump off the board.
// 
// Given the size of the board, the start position of the kingknight and the end position of the kingknight, your method will return how many possible ways there are of getting from start to end in exactly numMoves moves.  start and finish are vector <int>s each containing 2 elements.  The first element will be the (0-based) row position and the second will be the (0-based) column position.  Rows and columns will increment down and to the right respectively.  The board itself will have rows and columns ranging from 0 to size-1 inclusive.  
// 
// Note, two ways of getting from start to end are distinct if their respective move sequences differ in any way.  In addition, you are allowed to use spaces on the board (including start and finish) repeatedly during a particular path from start to finish.  We will ensure that the total number of paths is less than or equal to 2^63-1 (the upper bound for a long long).
// 
// DEFINITION
// Class:ChessMetric
// Method:howMany
// Parameters:int, vector <int>, vector <int>, int
// Returns:long long
// Method signature:long long howMany(int size, vector <int> start, vector <int> end, int numMoves)
// 
// 
// NOTES
// -For C++ users: long long is a 64 bit datatype and is specific to the GCC compiler.
// 
// 
// CONSTRAINTS
// -size will be between 3 and 100 inclusive
// -start will contain exactly 2 elements
// -finish will contain exactly 2 elements
// -Each element of start and finish will be between 1 and size-1 inclusive
// -numMoves will be between 1 and 50 inclusive
// -The total number of paths will be at most 2^63-1.
// 
// 
// EXAMPLES
// 
// 0)
// 3
// {0,0}
// {1,0}
// 1
// 
// Returns: 1
// 
// Only 1 way to get to an adjacent square in 1 move
// 
// 1)
// 3
// {0,0}
// {1,2}
// 1
// 
// Returns: 1
// 
// A single L-shaped move is the only way
// 
// 2)
// 3
// {0,0}
// {2,2}
// 1
// 
// Returns: 0
// 
// Too far for a single move
// 
// 3)
// 3
// {0,0}
// {0,0}
// 2
// 
// Returns: 5
// 
// Must count all the ways of leaving and then returning to the corner
// 
// 4)
// 100
// {0,0}
// {0,99}
// 50
// 
// Returns: 243097320072600
// 
// END KAWIGIEDIT TESTING
