#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <climits>
#include <cstring>
using namespace std;

typedef long long  int64;
typedef vector<int> vi;
typedef string ST;
typedef stringstream SS;
typedef vector< vector <int> > vvi;
typedef pair<int,int> ii;
typedef vector <string> vs;

#define endl 		("\n")
#define DEBUG(x)	cout << #x << " = " << x << "\n"
#define Pf		printf
#define	Sf		scanf

#define	ep		1e-9
#define PI		M_PI
#define E 		M_E

#define	CL(a, b)	memset(a, b, sizeof(a))
#define	mp		make_pair
#define	pb		push_back

#define	all(c)		(c).begin(), (c).end()
#define	tr(i, c)	for(__typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)

#define	present(x, c)	((c).find(x) != (c).end())		//map & set//
#define	cpresent(x, c)	(find(all(c),x) != (c).end())		//vector & list//

#define forn(i, n)	for(int i = 0, loop_ends_here = (int)n; i < loop_ends_here ; i++)
#define forab(i, a, b)	for(int i = a, loop_ends_here = (int)b; i <= loop_ends_here; i++)
#define rep(i, a, b)	for(int i = a, loop_ends_here = (int)b; i >= loop_ends_here; i--)

#define read(n)		scanf("%d", &n)
#define write(n)	printf("%d ", n)
#define writeln(n)	printf("%d\n", n)

class CreateGroups
{
public:
	int minChanges(vector <int> groups, int minSize, int maxSize);
};


int CreateGroups::minChanges (vector <int> groups, int minSize, int maxSize) 
{
	sort(all(groups));
	int ret = 0;
	int l = 0, r = groups.size() - 1;
	
	return ret;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, int p1, int p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << p1 << "," << p2;
	cout << "]" << endl;
	CreateGroups *obj;
	int answer;
	obj = new CreateGroups();
	clock_t startTime = clock();
	answer = obj->minChanges(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	int p1;
	int p2;
	int p3;
	
	{
	// ----- test 0 -----
	int t0[] = {10,20};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	p2 = 15;
	p3 = 5;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {20,8,6};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	p2 = 15;
	p3 = 6;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {10,20,30};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	p2 = 18;
	p3 = -1;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {50,10,20,20,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 15;
	p2 = 30;
	p3 = 20;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {100,200,301};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 200;
	p2 = 200;
	p3 = -1;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	int t0[] = {1,10,10};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 9;
	p2 = 20;
	p3 = -1;
	all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	int t0[] = {55,33,45,71,27,89,16,14,61};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 33;
	p2 = 56;
	p3 = 53;
	all_right = KawigiEdit_RunTest(6, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 7 -----
	int t0[] = {49,60,36,34,36,52,60,43,52,59};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 45;
	p2 = 51;
	p3 = 31;
	all_right = KawigiEdit_RunTest(7, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 8 -----
	int t0[] = {5,5,5,5,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 5;
	p2 = 5;
	p3 = 0;
	all_right = KawigiEdit_RunTest(8, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Your language school is starting a new semester, and each student must select a time schedule.  You are given a vector <int> groups, where the i-th element is the number of students who selected the i-th schedule.  Your school has a rule stating that the number of students assigned to each schedule must be between minSize and maxSize, inclusive.  However, this rule was not enforced properly during the sign up phase.  It is your job to reassign students in such a way that the rule is satisfied.  A reassignment is defined as removing a student from one time schedule and placing him in a different time schedule.  Return the minimal number of students you must reassign, or return -1 if it is impossible to satisfy the rule.  Note that you may not create new schedules or delete existing schedules.
// 
// DEFINITION
// Class:CreateGroups
// Method:minChanges
// Parameters:vector <int>, int, int
// Returns:int
// Method signature:int minChanges(vector <int> groups, int minSize, int maxSize)
// 
// 
// CONSTRAINTS
// -groups will contain between 1 and 50 elements, inclusive.
// -Each element of groups will be between 1 and 1,000,000, inclusive.
// -maxSize will be between 1 and 1,000,000, inclusive.
// -minSize will be between 1 and maxSize, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// {10,20}
// 10
// 15
// 
// Returns: 5
// 
// We can move 5 students from the second time schedule to the first. Both schedules will then have a size of 15, which is the maximum allowed size.
// 
// 1)
// {20,8,6}
// 10
// 15
// 
// Returns: 6
// 
// We can move 2 students from the first schedule to the second, and another 4 students from the first schedule to the third.  The sizes of the resulting schedules will be 14, 10 and 10.
// 
// 2)
// {10,20,30}
// 1
// 18
// 
// Returns: -1
// 
// There is no solution possible here.  We have 60 students in 3 time schedules, so it is impossible to have at most 18 students per schedule.
// 
// 3)
// {50,10,20,20,5}
// 15
// 30
// 
// Returns: 20
// 
// 
// 
// 4)
// {100,200,301}
// 200
// 200
// 
// Returns: -1
// 
// 
// 
// 5)
// {1,10,10}	
// 9
// 20
// 
// Returns: -1
// 
// 
// 
// 6)
// {55,33,45,71,27,89,16,14,61}
// 33
// 56
// 
// Returns: 53
// 
// 
// 
// 7)
// {49,60,36,34,36,52,60,43,52,59}
// 45
// 51
// 
// Returns: 31
// 
// 
// 
// 8)
// {5,5,5,5,5}
// 5
// 5
// 
// Returns: 0
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
