#include <bits/stdc++.h>
using namespace std;

class EmoticonsDiv1
{
public:
	int printSmiles(int smiles);
};

const int sz = 2e3+1;

int dp[sz][sz];

class Node {
public:
    int steps, paste, copy;
    Node(int s, int p, int c) : steps(s), paste(p), copy(c){}
};

bool inRange(int x) {
    return x >= 0 && x < sz;
}

int EmoticonsDiv1::printSmiles (int smiles)
{
    memset(dp, -1, sizeof(dp));

    queue <Node> q;
    q.push(Node(0, 1, 0));
    dp[1][0] = 0;

    while(!q.empty()) {
        Node nd = q.front();
        q.pop();
        //if(nd.steps < 9)
            //printf("steps = %d, paste = %d, copy = %d\n", nd.steps, nd.paste, nd.steps);

        if(nd.paste == smiles)
            return nd.steps;

        Node n(nd);
        n.steps++;
        n.copy = n.paste;
        if(inRange(n.steps) && inRange(n.paste) && inRange(n.copy) && dp[n.paste][n.copy] == -1) {
            dp[n.paste][n.copy] = n.steps;
            q.push(n);
        }

        n = nd;
        n.steps++;
        n.paste += n.copy;
        if(n.copy > 0 && inRange(n.steps) && inRange(n.paste) && inRange(n.copy) && dp[n.paste][n.copy] == -1) {
            dp[n.paste][n.copy] = n.steps;
            q.push(n);
        }

        n = nd;
        n.steps++;
        n.paste--;
        if(n.paste > 0 && inRange(n.steps) && inRange(n.paste) && inRange(n.copy) && dp[n.paste][n.copy] == -1) {
            dp[n.paste][n.copy] = n.steps;
            q.push(n);
        }
    }

    return -1;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << p0;
	cout << "]" << endl;
	EmoticonsDiv1 *obj;
	int answer;
	obj = new EmoticonsDiv1();
	clock_t startTime = clock();
	answer = obj->printSmiles(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	int p1;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 2;
	p1 = 2;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 4;
	p1 = 4;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 6;
	p1 = 5;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 18;
	p1 = 8;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 4 -----
	disabled = false;
	p0 = 11;
	p1 = 8;
	all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 5 -----
	disabled = false;
	p0 = 1000;
	all_right = (disabled || KawigiEdit_RunTest(5, p0, false, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// You are very happy because you advanced to the next round of a very important programming contest.
// You want your best friend to know how happy you are.
// Therefore, you are going to send him a lot of smile emoticons.
// You are given an int smiles: the exact number of emoticons you want to send.
// 
// You have already typed one emoticon into the chat.
// Then, you realized that typing is slow.
// Instead, you will produce the remaining emoticons using copy, paste, and possibly some deleting.
// 
// You can only do three different operations:
// 
// Copy all the emoticons you currently have into the clipboard.
// Paste all emoticons from the clipboard.
// Delete one emoticon from the message.
// 
// Each operation takes precisely one second.
// Copying replaces the old content of the clipboard.
// Pasting does not empty the clipboard.
// You are not allowed to copy just a part of the emoticons you already have.
// You are not allowed to delete an emoticon from the clipboard.
// 
// Return the smallest number of seconds in which you can turn the one initial emoticon into smiles emoticons.
// 
// DEFINITION
// Class:EmoticonsDiv1
// Method:printSmiles
// Parameters:int
// Returns:int
// Method signature:int printSmiles(int smiles)
// 
// 
// CONSTRAINTS
// -smiles will be between 2 and 1000, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// 2
// 
// Returns: 2
// 
// First use copy, then use paste. The first operation copies one emoticon into the clipboard, the second operation pastes it into the message, so now you have two emoticons and you are done.
// 
// 1)
// 4
// 
// Returns: 4
// 
// One optimal solution is to copy the initial emoticon and then to paste it three times. Another optimal solution is to copy the one emoticon, paste it, copy the two emoticons you currently have, and paste two more.
// 
// 2)
// 6
// 
// Returns: 5
// 
// 
// Copy. This puts one emoticon into the clipboard.
// Paste. You now have 2 emoticons in the message.
// Copy. The clipboard now contains 2 emoticons.
// Paste. You now have 4 emoticons in the message.
// Paste. You now have 6 emoticons in the message and you are done.
// 
// 
// 3)
// 18
// 
// Returns: 8
// 
// 
// 
// 4)
// 11
// 
// Returns: 8
// 
// Sometimes we actually do delete an emoticon in the optimal solution.
// 
// END KAWIGIEDIT TESTING
