#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <climits>
#include <cstring>
#include <iterator>
#include <fstream>
using namespace std;

typedef long long  int64;
typedef vector<int> vi;
typedef string ST;
typedef stringstream SS;
typedef vector< vector <int> > vvi;
typedef pair<int,int> ii;
typedef vector <string> vs;

#define DEBUG(x)	cout << #x << " = " << x << "\n"
#define endl 		("\n")

#define	ep		1e-9
#define PI		M_PI
#define E 		M_E

#define	CL(a, b)	memset(a, b, sizeof(a))
#define	mp		make_pair
#define	pb		push_back

#define	all(c)		(c).begin(), (c).end()
#define	tr(i, c)	for(__typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)

#define	present(x, c)	((c).find(x) != (c).end())		//map & set//
#define	cpresent(x, c)	(find(all(c),x) != (c).end())		//vector & list//

#define forn(i, n)	for(int i = 0, loop_ends_here = (int)n; i < loop_ends_here ; i++)
#define forab(i, a, b)	for(int i = a, loop_ends_here = (int)b; i <= loop_ends_here; i++)
#define rep(i, a, b)	for(int i = a, loop_ends_here = (int)b; i >= loop_ends_here; i--)

#define Pf		printf
#define	Sf		scanf

#define read(n)		scanf("%d", &n)
#define write(n)	printf("%d ", n)
#define writeln(n)	printf("%d\n", n)

/*
#ifdef DEBUG
	#undef DEBUG
#endif
#define DEBUG
*/

class FairWorkload
{
public:
	int getMostWork(vector <int> folders, int workers);
};

vi folders;
int workers, N;

bool isValidPartition(int val) {
	vi partition(1, 0);
	tr(it, folders) {
		if(partition.back() + *it <= val)
			partition.back() += *it;
		else
			partition.pb(*it);
		if(partition.back() > val || *it > val)
			return false;
	}
	return partition.size() <= workers;
}

int binarySearch(int low = *min_element(all(folders)), int high = accumulate(all(folders), 0)) {
	if(low == high)	return low;

	int mid = (low + high)/2;
	return isValidPartition(mid) ? binarySearch(low, mid) : binarySearch(mid+1, high);
}

int FairWorkload::getMostWork (vector <int> folders, int workers) {
	::folders = folders, ::workers = workers, N = folders.size();
	return binarySearch();
}

/*
vi folders;
int workers, N;

int sum[20][20];
int Ans[20][20];

int Sum(int l, int r) {
	int &ret = sum[l][r];
	if(ret > -1)
		return ret;
	return ret = folders[l] + ( l == r ? 0 : Sum(l+1, r) );
}

const int INF = (int)1E8;

int solve(int idx = 0, int k = workers) {
	if(N - idx == 0 && k == 0)	return 0;
	if(N - idx == 0 || k == 0)	return INF;

	int &ret = Ans[idx][k];
	if(ret > -1)
		return ret;

	ret = INF;

	forab(i, idx, N-1) {
		ret = min(ret, max(Sum(idx, i), solve(i+1, k-1)));
	}

	return ret;
}

int FairWorkload::getMostWork (vector <int> folders, int workers) 
{
	DEBUG(INF);
	::folders = folders;
	::workers = workers;
	N = folders.size();
	CL(sum, -1);
	CL(Ans, -1);
	return solve();
}
*/

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << p1;
	cout << "]" << endl;
	FairWorkload *obj;
	int answer;
	obj = new FairWorkload();
	clock_t startTime = clock();
	answer = obj->getMostWork(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	int p1;
	int p2;
	
	{
	// ----- test 0 -----
	int t0[] = {10,20,30,40,50,60,70,80,90};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 3;
	p2 = 170;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {10,20,30,40,50,60,70,80,90};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 5;
	p2 = 110;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {568,712,412,231,241,393,865,287,128,457,238,98,980,23,782};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 4;
	p2 = 1785;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1000};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2;
	p2 = 1000;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {50,50,50,50,50,50,50};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2;
	p2 = 200;
	all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	int t0[] = {1,1,1,1,100};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 5;
	p2 = 100;
	all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	int t0[] = {950,650,250,250,350,100,650,150,150,700};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 6;
	p2 = 950;
	all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Fabian is in charge of a law firm working on an important case.  For a case coming up, he needs a specific folder which is stored in one of the filing cabinets arranged in a line against the wall of the records room.  He has assigned a number of workers to find the folder from the filing cabinets.  He doesn't want the workers to get in each other's way, nor does he want folders from different filing cabinets getting mixed up, so he has decided to partition the cabinets, and assign a specific section to each worker.  Each worker will have at least 1 cabinet to search through.
// 
// More specifically, Fabian wants to divide the line of filing cabinets into N sections (where N is the number of workers) so that every cabinet that the ith worker looks through is earlier in the line than every cabinet that the jth worker has to look through, for i < j.
// 
// His initial thought was to make all the sections equal, giving each worker the same number of filing cabinets to look through, but then he realized that the filing cabinets differed in the number of folders they contained.  He now has decided to partition the filing cabinets so as to minimize the maximum number of folders that a worker would have to look through.  For example, suppose there were three workers and nine filing cabinets with the following number of folders:
// 10 20 30 40 50 60 70 80 90
// 
// He would divide up the filing cabinets into the following sections:
// 10 20 30 40 50 | 60 70 | 80 90
// 
// The worker assigned to the first section would have to look through 150 folders. The worker assigned to the second section would have to search through 130 folders, and the last worker would filter through 170 folders. In this partitioning, the maximum number of folders that a worker looks through is 170.  No other partitioning has less than 170 folders in the largest partition.
// 
// Write a class FairWorkload with a method getMostWork which takes a vector <int> folders (the number of folders for each filing cabinet) and an int workers (the number of workers).  The method should return an int which is the maximum amount of folders that a worker would have to look through in an optimal partitioning of the filing cabinets.  For the above example, the method would have returned 170.
// 
// DEFINITION
// Class:FairWorkload
// Method:getMostWork
// Parameters:vector <int>, int
// Returns:int
// Method signature:int getMostWork(vector <int> folders, int workers)
// 
// 
// CONSTRAINTS
// -folders will contain between 2 and 15 elements, inclusive
// -Each element of folders will be between 1 and 1000, inclusive
// -workers will be between 1 and the number of elements in folders, inclusive
// 
// 
// EXAMPLES
// 
// 0)
// { 10, 20, 30, 40, 50, 60, 70, 80, 90 }
// 3
// 
// Returns: 170
// 
// This is the example from above.
// 
// 1)
// { 10, 20, 30, 40, 50, 60, 70, 80, 90 }
// 5
// 
// Returns: 110
// 
// With the addition of two more workers, it makes more sense to partition the books as follows:
// 
// 	10 20 30 40 | 50 60 | 70 | 80 | 90
// 
// 
// The most folders that any single worker must look through will be 110.
// 
// 2)
// { 568, 712, 412, 231, 241, 393, 865, 287, 128, 457, 238, 98, 980, 23, 782 }
// 4
// 
// Returns: 1785
// 
// The filing cabinets should be partitioned as follows:
// 
// 	568 712 412 | 231 241 393 865 | 287 128 457 238 98 | 980 23 782
// 
// 
// 3)
// { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1000 }
// 2
// 
// Returns: 1000
// 
// The only fair partitioning gives the 14 cabinets with 1 folder to one worker, and the last cabinet with 1000 folders to the other worker.
// 
// 4)
// { 50, 50, 50, 50, 50, 50, 50 }
// 2
// 
// Returns: 200
// 
// There are two valid partitions:
// 	50 50 50 | 50 50 50 50
// 	50 50 50 50 | 50 50 50
// 
// Both of these partitions result in a maximum of 200 folders for any worker.
// 
// 5)
// {1,1,1,1,100}
// 5
// 
// Returns: 100
// 
// With 5 workers, each worker gets a filing cabinet, and the most folders that any worker has to look through will be 100.
// 
// 6)
// { 950, 650, 250, 250, 350, 100, 650, 150, 150, 700 }
// 6
// 
// Returns: 950
// 
// With 6 workers, the maximum amount of folders that any worker would have to look through is 950.  There are 25 different ways of partitioning the filing cabinets to produce this maximum:
// 
// 	950 | 650 | 250 | 250 350 | 100 650 150 | 150 700
// 	950 | 650 | 250 | 250 350 100 | 650 150 | 150 700
// 	950 | 650 | 250 | 250 350 100 | 650 150 150 | 700
// 	950 | 650 | 250 250 | 350 | 100 650 150 | 150 700
// 	950 | 650 | 250 250 | 350 100 | 650 150 | 150 700
// 	950 | 650 | 250 250 | 350 100 | 650 150 150 | 700
// 	950 | 650 | 250 250 350 | 100 | 650 150 | 150 700
// 	950 | 650 | 250 250 350 | 100 | 650 150 150 | 700
// 	950 | 650 | 250 250 350 | 100 650 | 150 | 150 700
// 	950 | 650 | 250 250 350 | 100 650 | 150 150 | 700
// 	950 | 650 | 250 250 350 | 100 650 150 | 150 | 700
// 	950 | 650 | 250 250 350 100 | 650 | 150 | 150 700
// 	950 | 650 | 250 250 350 100 | 650 | 150 150 | 700
// 	950 | 650 | 250 250 350 100 | 650 150 | 150 | 700
// 	950 | 650 250 | 250 | 350 | 100 650 150 | 150 700
// 	950 | 650 250 | 250 | 350 100 | 650 150 | 150 700
// 	950 | 650 250 | 250 | 350 100 | 650 150 150 | 700
// 	950 | 650 250 | 250 350 | 100 | 650 150 | 150 700
// 	950 | 650 250 | 250 350 | 100 | 650 150 150 | 700
// 	950 | 650 250 | 250 350 | 100 650 | 150 | 150 700
// 	950 | 650 250 | 250 350 | 100 650 | 150 150 | 700
// 	950 | 650 250 | 250 350 | 100 650 150 | 150 | 700
// 	950 | 650 250 | 250 350 100 | 650 | 150 | 150 700
// 	950 | 650 250 | 250 350 100 | 650 | 150 150 | 700
// 	950 | 650 250 | 250 350 100 | 650 150 | 150 | 700
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
