#include <iostream>
#include <ctime>
#include <vector>
#include <list>
#include <queue>
#include <map>
#include <set>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <cassert>
#include <utility>
#include <sstream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <climits>
#include <iterator>
#include <fstream>
using namespace std;

typedef long long 		int64;
typedef vector<int> 		vi;
typedef string 			ST;
typedef stringstream 		SS;
typedef vector< vector<int> > 	vvi;
typedef pair<int,int> 		ii;
typedef vector<string> 		vs;
/*
#if __cplusplus > 199711L	// for g++0x, value of __cplusplus must be greater thana 199711L.
	#define tr(i, c)	for(auto i = begin(c); i != end(c); i++)
#else
	#define tr(i, c)	for(typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)
#endif
*/
#define endl		("\n")
#define tr(i, c)	for(__typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)
#define PI		M_PI
#define E 		M_E
#define	eps		1e-9

#define	Sf		scanf
#define	Pf		printf

#define forn(i, n)	for(int i = 0, lets_stop_here = (int)n; i <  lets_stop_here; i++)
#define forab(i, a, b)	for(int i = a, lets_stop_here = (int)b; i <= lets_stop_here; i++)
#define rep(i, a, b)	for(int i = a, lets_stop_here = (int)b; i >= lets_stop_here; i--)

#define	all(c)		(c).begin(), (c).end()
#define	cl(a, b)	memset(a, b, sizeof(a))
#define mp		make_pair
#define pb		push_back

#define	present(x, c)	((c).find(x) != (c).end())	//map & set//
#define	cpresent(x, c)	(find( (c).begin(), (c).end(), x) != (c).end())	//vector & list//

#define read(n)		scanf("%d", &n)
#define write(n)	printf("%d ", n)
#define writeln(n)	printf("%d\n", n)

#if (0)
	#define debug 
#else 
	#define debug(x)	cout << #x << " = " << x << "\n"
#endif

class GooseInZooDivOne
{
public:
	int count(vector <string> field, int dist);
};

int N, M;
const int64 mod = 1e9 + 7;
//const int sz = 55*55;
//int64 fact[sz];

vector <string> field;

bool valid(int x, int y) {
	return x >= 0 && x < N && y >= 0 && y < M && field[x][y] == 'v';
}

int dfs(int x, int y, int d) {
	if(!valid(x, y))
		return 0;
	field[x][y] = '.';
	int ret = 1;
	forn(i, N)	forn(j, M) {
		if(abs(x-i) + abs(y-j) <= d)
			ret += dfs(i, j, d);
	}
	return ret;
}

int64 power(int64 a, int64 n) {
	if(n == 0)
		return 1ll;
	int64 tmp = power(a, n/2);
	tmp = (tmp*tmp) % mod;
	if(n % 2 == 1)
		tmp = (a*tmp) % mod;
	return tmp;
}
/*
int64 inv(int64 a) {
	return power(a, mod-2);
}

int64 C(int n, int r) {
	int64 ret = fact[n];
	ret = (ret * inv(r) ) % mod;
	ret = (ret * inv(n-r)) % mod;
	return ret;
}
*/
int GooseInZooDivOne::count (vector <string> _field, int dist) 
{
/*
	fact[0] = 1;
	forab(i, 1, sz-1)
		fact[i] = (i*fact[i-1]) % mod;
*/
	field = _field;
	N = field.size(); M = field.back().size();
	int even = 0, odd = 0;

//	vi cnt;
	forn(x, N)	forn(y, M) {
		int tmp = dfs(x, y, dist);
		if(tmp > 0) {
//			cnt.pb(tmp);
			if(tmp % 2 == 0)
				even++;
			else
				odd++;
		}
	}

/*
	tr(it, cnt)
		write(*it);
	cout << endl;
	debug(even);
	debug(odd);
*/
	if(odd == 0)
		return (power(2, even)+mod-1) % mod;
	int64 ret =  ((power(2, odd-1) + mod-1) % mod + ((power(2, even)+mod-1)*power(2, odd-1) ) % mod) % mod;
	ret = (ret + mod ) % mod;
	return ret;
/*
	if(even == 0 && odd <= 1)
		return 0;
	if(odd == 0) {
		return (power(2, even) + mod -1 ) % mod;
	}

	int ret = (power(2, odd-1) + mod -1) % mod;

	forab(k, 1, even) {
		ret += (C(even, k) * power(2, odd-1)) % mod; 
		ret %= mod;
	}
	
	return ret;
*/
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << p1;
	cout << "]" << endl;
	GooseInZooDivOne *obj;
	int answer;
	obj = new GooseInZooDivOne();
	clock_t startTime = clock();
	answer = obj->count(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	int p2;
	
	{
	// ----- test 0 -----
	string t0[] = {"vvv"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	p2 = 3;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 100;
	p2 = 0;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"vvv"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	p2 = 0;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"v.v..................v............................",".v......v..................v.....................v","..v.....v....v.........v...............v......v...",".........vvv...vv.v.........v.v..................v",".....v..........v......v..v...v.......v...........","...................vv...............v.v..v.v..v...",".v.vv.................v..............v............","..vv.......v...vv.v............vv.....v.....v.....","....v..........v....v........v.......v.v.v........",".v.......v.............v.v..........vv......v.....","....v.v.......v........v.....v.................v..","....v..v..v.v..............v.v.v....v..........v..","..........v...v...................v..............v","..v........v..........................v....v..v...","....................v..v.........vv........v......","..v......v...............................v.v......","..v.v..............v........v...............vv.vv.","...vv......v...............v.v..............v.....","............................v..v.............."
			"...v",".v.............v.......v..........................","......v...v........................v..............",".........v.....v..............vv..................","................v..v..v.........v....v.......v....","........v.....v.............v......v.v............","...........v....................v.v....v.v.v...v..","...........v......................v...v...........","..........vv...........v.v.....................v..",".....................v......v............v...v....",".....vv..........................vv.v.....v.v.....",".vv.......v...............v.......v..v.....v......","............v................v..........v....v....","................vv...v............................","................v...........v........v...v....v...","..v...v...v.............v...v........v....v..v....","......v..v.......v........v..v....vv..............","...........v..........v........v.v................","v.v......v................v....................v..",".v........v............................."
			"...v......","............................v...v.......v.........","........................vv.v..............v...vv..",".......................vv........v.............v..","...v.............v.........................v......","....v......vv...........................v.........","....vv....v................v...vv..............v..","..................................................","vv........v...v..v.....v..v..................v....",".........v..............v.vv.v.............v......",".......v.....v......v...............v.............","..v..................v................v....v......",".....v.....v.....................v.v......v......."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 3;
	p2 = 898961330;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"vv.vv",".....","vv.vv",".....","v.v.v"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	all_right = KawigiEdit_RunTest(4, p0, p1, false, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Crow Keith is looking at the goose cage in the zoo.
// The bottom of the cage is divided into a grid of square cells.
// There are some birds sitting on those cells (with at most one bird per cell).
// Some of them are geese and all the others are ducks.
// 
// Keith wants to know which birds are geese.
// He knows the following facts about them:
// 
// There is at least one goose in the cage.
// The number of geese is even.
// Each bird within Manhattan distance dist of any goose is also a goose.
// 
//  
// You are given a vector <string> field and the int dist.
// The array field describes the bottom of the cage.
// Each character of each element of field describes one of the cells.
// The meaning of individual characters follows.
// 
// The character 'v' represents a cell that contains a bird.
// The character '.' represents an empty cell.
// 
// 
// Return the number of possible sets of geese in the cage, modulo 1,000,000,007.
// Note that for some of the test cases there can be no possible sets of geese.
// 
// DEFINITION
// Class:GooseInZooDivOne
// Method:count
// Parameters:vector <string>, int
// Returns:int
// Method signature:int count(vector <string> field, int dist)
// 
// 
// NOTES
// -The Manhattan distance between cells (a,b) and (c,d) is |a-c| + |b-d|, where || denotes absolute value. In words, the Manhattan distance is the smallest number of steps needed to get from one cell to the other, given that in each step you can move to a cell that shares a side with your current cell.
// 
// 
// CONSTRAINTS
// -field will contain between 1 and 50 elements, inclusive.
// -Each element of field will contain between 1 and 50 characters, inclusive.
// -Each element of field will contain the same number of characters.
// -Each character of each element of field will be 'v' or '.'.
// -dist will be between 0 and 100, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// {"vvv"}
// 0
// 
// Returns: 3
// 
// There are three possible sets of positions of geese: "ggd", "gdg", or "dgg" ('g' are geese and 'd' are ducks).
// 
// 1)
// {"."}
// 100
// 
// Returns: 0
// 
// The number of geese must be positive, but there are no birds in the cage.
// 
// 2)
// {"vvv"}
// 1
// 
// Returns: 0
// 
// 
// 
// 3)
// {"v.v..................v............................"
// ,".v......v..................v.....................v"
// ,"..v.....v....v.........v...............v......v..."
// ,".........vvv...vv.v.........v.v..................v"
// ,".....v..........v......v..v...v.......v..........."
// ,"...................vv...............v.v..v.v..v..."
// ,".v.vv.................v..............v............"
// ,"..vv.......v...vv.v............vv.....v.....v....."
// ,"....v..........v....v........v.......v.v.v........"
// ,".v.......v.............v.v..........vv......v....."
// ,"....v.v.......v........v.....v.................v.."
// ,"....v..v..v.v..............v.v.v....v..........v.."
// ,"..........v...v...................v..............v"
// ,"..v........v..........................v....v..v..."
// ,"....................v..v.........vv........v......"
// ,"..v......v...............................v.v......"
// ,"..v.v..............v........v...............vv.vv."
// ,"...vv......v...............v.v..............v....."
// ,"............................v..v.................v"
// ,".v.............v.......v.........................."
// ,"......v...v........................v.............."
// ,".........v.....v..............vv.................."
// ,"................v..v..v.........v....v.......v...."
// ,"........v.....v.............v......v.v............"
// ,"...........v....................v.v....v.v.v...v.."
// ,"...........v......................v...v..........."
// ,"..........vv...........v.v.....................v.."
// ,".....................v......v............v...v...."
// ,".....vv..........................vv.v.....v.v....."
// ,".vv.......v...............v.......v..v.....v......"
// ,"............v................v..........v....v...."
// ,"................vv...v............................"
// ,"................v...........v........v...v....v..."
// ,"..v...v...v.............v...v........v....v..v...."
// ,"......v..v.......v........v..v....vv.............."
// ,"...........v..........v........v.v................"
// ,"v.v......v................v....................v.."
// ,".v........v................................v......"
// ,"............................v...v.......v........."
// ,"........................vv.v..............v...vv.."
// ,".......................vv........v.............v.."
// ,"...v.............v.........................v......"
// ,"....v......vv...........................v........."
// ,"....vv....v................v...vv..............v.."
// ,".................................................."
// ,"vv........v...v..v.....v..v..................v...."
// ,".........v..............v.vv.v.............v......"
// ,".......v.....v......v...............v............."
// ,"..v..................v................v....v......"
// ,".....v.....v.....................v.v......v......."}
// 3
// 
// Returns: 898961330
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
