#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <climits>
#include <cstring>
using namespace std;

typedef long long  int64;
typedef vector<int> vi;
typedef string ST;
typedef stringstream SS;
typedef vector< vector <int> > vvi;
typedef pair<int,int> ii;
typedef vector <string> vs;

#define Pf	printf
#define	Sf	scanf

#define	ep	1e-9
#define PI M_PI
#define E M_E

#define	CL(a, b)	memset(a, b, sizeof(a))
#define	mp	make_pair

#define	pb	push_back

#define	all(c)	(c).begin(), (c).end()
#define	tr(i, c)	for(typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)

#define	present(x, c)	((c).find(x) != (c).end())		//map & set//
#define	cpresent(x, c)	(find(all(c),x) != (c).end())	//vector & list//

#define forn(i, n)	for(int i = 0, loop_ends_here = (int)n; i < loop_ends_here; i++)
#define forab(i, a, b)	for(int i = a, loop_ends_here = (int) b; i <= loop_ends_here; i++)
#define rep(i, a, b)	for(int i = a, loop_ends_here = (int)b; i>=loop_ends_here; i--)

class HealthFood
{
public:
	vi protien, carbs, fat, calorie;
	bool in[111];
	ST diet;

	void process(int idx) {
		if(idx == diet.size())	return;
		vi *vt;
		
		switch(tolower(diet[idx])) {
			case 'c': 	vt = &carbs;	break;
			case 'p':	vt = &protien;	break;
			case 'f':	vt = &fat;		break;
			case 't':	vt = &calorie;	break;
			default:	cout << "error#1\n";
		}
		vi &v = *vt;
		
		int mm;
		if(isupper(diet[idx])) {
			mm = -1;
			forn(i, v.size())	if(in[i])
				mm = max(mm, v[i]);
		}
		else {
			mm = 999999;
			forn(i, v.size())	if(in[i])
				mm = min(mm, v[i]);
		}
		
		forn(i, v.size())	if(in[i]) {
			if(mm != v[i])	in[i] = false;
		}
/*		
		forn(i, v.size())
			Pf("%d ", (in[i] ? 1:0));
		cout << endl;
*/		
		process(idx+1);
	}

	vector <int> selectMeals(vector <int> _protein, vector <int> _carbs, vector <int> _fat, vector <string> dietPlans)
	{
		protien = _protein,	carbs = _carbs, 	fat = _fat;
		vector <int> ret;
		
		forn(i, fat.size())
			calorie.pb(fat[i]*9+carbs[i]*5 + protien[i]*5);
/*			
		cout << "Protien(p)  : ";
		tr(it, protien)	Pf("%4d ", *it);
		cout << endl;
		
		cout << "Carbs(c)    : ";
		tr(it, carbs)	Pf("%4d ", *it);
		cout << endl;
		
		cout << "Fat(f)      : ";
		tr(it, fat)	Pf("%4d ", *it);
		cout << endl;
		
		cout << "Calorie(t)  : ";
		tr(it, calorie)	Pf("%4d ", *it);
		cout << endl;
*/			
		tr(it, dietPlans) {
			diet = *it;
			CL(in, -1);
			
//			cout << diet << endl;
			process(0);
			forn(i, protien.size())	if(in[i]) {
				ret.pb(i);	break;
			}
//			cout << endl;
		}
		
		return ret;
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, vector <int> p2, vector <string> p3, bool hasAnswer, vector <int> p4) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p3.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p3[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	HealthFood *obj;
	vector <int> answer;
	obj = new HealthFood();
	clock_t startTime = clock();
	answer = obj->selectMeals(p0, p1, p2, p3);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p4.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << p4[i];
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << answer[i];
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p4.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p4[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <int> p1;
	vector <int> p2;
	vector <string> p3;
	vector <int> p4;
	
	{
	// ----- test 0 -----
	int t0[] = {3,4};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,8};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {5,2};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	string t3[] = {"P","p","C","c","F","f","T","t"};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	int t4[] = {1,0,1,0,0,1,1,0};
			p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {3,4,1,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,8,5,1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {5,2,4,4};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	string t3[] = {"tFc","tF","Ftc"};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	int t4[] = {3,2,0};
			p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {18,86,76,0,34,30,95,12,21};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {26,56,3,45,88,0,10,27,53};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {93,96,13,95,98,18,59,49,86};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	string t3[] = {"f","Pt","PT","fT","Cp","C","t","","cCp","ttp","PCFt","P","pCt","cP","Pc"};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	int t4[] = {2,6,6,2,4,4,5,0,5,5,6,6,3,5,6};
			p4.assign(t4, t4 + sizeof(t4) / sizeof(t4[0]));
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Your favorite local restaurant has caught onto the health food trend, and has begun publishing basic nutritional information for all of their most popular menu selections.  This is excellent timing, since your doctor has recently recommended various diet plans for you and several of your friends.
// 
// You are given vector <int> protein, vector <int> carbs, and vector <int> fat, representing the number of grams of protein, carbs, and fat in each of the available menu items.  Elements from each vector <int> correspond to the elements of the other vector <int>s with the same index.
// 
// You are also given a vector <string> dietPlans, indicating the doctor's recommendation for how each person should make their meal selection.  Each element of dietPlans describes the diet plan for an individual.  Each character of each element of dietPlans specifies, in order of importance, a selection criteria, defined in the following way:
// 
// 'C' = high carbs
// 'c' = low carbs
// 'P' = high protein
// 'p' = low protein
// 'F' = high fat
// 'f' = low fat
// 'T' = high calorie
// 't' = low calorie
// 
// 
// 
// As an example, the diet plan "tf" means the doctor recommends a meal with the lowest possible calories, and if more than one is tied, the one with less fat should be selected.  Whenever more than one meal is tied according to the diet plan, then the one with a lower index should be selected.
// 
// The restaurant sloppily neglected to list the total calorie count on the menu.  Fortunately, you happen to remember from days gone by that one gram of fat contains 9 calories, and one gram of carbs or protein contains 5 calories.
// 
// You are to return a vector <int> indicating the indexes of the menu selections that best suit each person's diet plan (indexed from 0).  The return vector <int> should have the same number of elements as dietPlans, and each value of the return vector <int> should correspond to the element of dietPlans with the same index.
// 
// 
// DEFINITION
// Class:HealthFood
// Method:selectMeals
// Parameters:vector <int>, vector <int>, vector <int>, vector <string>
// Returns:vector <int>
// Method signature:vector <int> selectMeals(vector <int> protein, vector <int> carbs, vector <int> fat, vector <string> dietPlans)
// 
// 
// NOTES
// -When no diet plan is specified, the default should be the menu selection with the lowest index (0).
// 
// 
// CONSTRAINTS
// -carbs will contain between 1 and 50 elements, inclusive
// -protein will contain between 1 and 50 elements, inclusive
// -fat will contain between 1 and 50 elements, inclusive.
// -carbs, protein, and fat will each contain the same number of elements.
// -Each element of carbs, protein, and fat will be between 0 and 100, inclusive.
// -dietPlans will contain between 1 and 50 elements, inclusive.
// -Each element of dietPlans will be between 0 and 4 characters in length, inclusive, and will contain only the characters "CcPpFfTt".
// 
// 
// EXAMPLES
// 
// 0)
// {3, 4}
// {2, 8}
// {5, 2}
// {"P", "p", "C", "c", "F", "f", "T", "t"}
// 
// Returns: { 1,  0,  1,  0,  0,  1,  1,  0 }
// 
// This is a simple menu, with only two selections.  We see each of the simplest diet plans here.
// 
// 1)
// {3, 4, 1, 5}
// {2, 8, 5, 1}
// {5, 2, 4, 4}
// {"tFc", "tF", "Ftc"}
// 
// Returns: { 3,  2,  0 }
// 
// Note here that lowest total calories is tied between items 2 and 3.  Note also that both of those items are tied for fat content.  So, when we have lowest carbs as a tie-breaker, item 3 is selected.  When there is no further tiebreaker, we select the one with lowest index.  Note also that if highest fat is the first requirement, then the tiebreaker is irrelevant since item 0 has more fat than items 2 or 3.
// 
// 2)
// {18, 86, 76,  0, 34, 30, 95, 12, 21}
// {26, 56,  3, 45, 88,  0, 10, 27, 53}
// {93, 96, 13, 95, 98, 18, 59, 49, 86}
// {"f", "Pt", "PT", "fT", "Cp", "C", "t", "",
//  "cCp", "ttp", "PCFt", "P", "pCt", "cP", "Pc"}
// 
// 
// Returns: { 2,  6,  6,  2,  4,  4,  5,  0,  5,  5,  6,  6,  3,  5,  6 }
// 
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
