#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <climits>
#include <cstring>
using namespace std;

typedef long long  int64;
typedef vector<int> vi;
typedef string ST;
typedef stringstream SS;
typedef vector< vector <int> > vvi;
typedef pair<int,int> ii;
typedef vector <string> vs;

#define Pf	printf
#define	Sf	scanf

#define	ep	1e-9
#define PI M_PI
#define E M_E

#define	CL(a, b)	memset(a, b, sizeof(a))
#define	mp	make_pair

#define	pb	push_back
#define	SZ(a)	int((a).size())

#define	all(c)	(c).begin(), (c).end()
#define	tr(i, c)	for(typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)

#define	present(x, c)	((c).find(x) != (c).end())		//map & set//
#define	cpresent(x, c)	(find(all(c),x) != (c).end())	//vector & list//

#define	forn(i, n)	for(int i = 0; i < n; i++)
#define	forab(i, a, b)	for(int i = a; i <= b; i++)
#define	rep(i, a, b)	for(int i = a; i>=b; i--)

class MathContest
{
	char ch[200000];
	string seq;
	int rep;
	void PreProcess() {
		forn(i, seq.length()*rep)
			ch[i] = seq[i%seq.length()];
	ch[seq.length()*rep] = '\0';
	}

public:
	int countBlack(string ballSequence, int repetitions)
	{
		rep = repetitions;
		seq = ballSequence;
		PreProcess();
		int ret = 0;

		int st = 0, t = rep*seq.length()-1;
		bool flip = false, rev = false;

		while(st <= t) {
			char c = rev? ch[t--] : ch[st++];
			if (flip)
				c = c == 'B' ? 'W' : 'B';
			if(c == 'B')
				ret++, flip = !flip;
			else
				rev = !rev;
		}
		

		return ret;
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, string p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"" << "," << p1;
	cout << "]" << endl;
	MathContest *obj;
	int answer;
	obj = new MathContest();
	clock_t startTime = clock();
	answer = obj->countBlack(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	string p0;
	int p1;
	int p2;
	
	{
	// ----- test 0 -----
	p0 = "BBWWB";
	p1 = 1;
	p2 = 2;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = "BBB";
	p1 = 10;
	p2 = 1;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = "BW";
	p1 = 10;
	p2 = 20;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = "WWWWWWWBWWWWWWWWWWWWWW";
	p1 = 1;
	p2 = 2;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// The most famous math contest is going to start soon. As usual in math contests, there is going to be a problem that involves an abstract machine of sorts and predicting how will it process a sequence of colored balls. This time, the machine will use the balls as a special language that works as follows: The process begins when the machine is given a stack of balls that are colored either white or black. The next steps are as follows:
// Take the top ball out of the stack, show it to the audience and discard it.
// If the taken ball was white, the contents of the stack will be dumped into a new stack and the new stack will be used in the next step. In other words, the order of the balls in the stack will be reversed.
// If the taken ball was black, the balls inside the stack will get their colors inverted. Every originally-white ball will turn black and every originally-black ball will turn white.
// The process is repeated until there are no balls left in the stack.
// 
// You have been hired to make a program to grade the answers to this contest question. Given the contents of the stack, return the number of black balls that will be shown to the audience. Due to limitations in the input size, the contents of the stack are given by string ballSequence, and int repetitions. To form the sequence of balls, repeat ballSequence repetitions times. The final sequence will contain 'B' and 'W' characters denoting a black or a white ball respectively from the top of the stack to the bottom.
// 
// DEFINITION
// Class:MathContest
// Method:countBlack
// Parameters:string, int
// Returns:int
// Method signature:int countBlack(string ballSequence, int repetitions)
// 
// 
// CONSTRAINTS
// -ballSequence will contain between 1 and 50 characters, inclusive.
// -Each character in ballSequence will be 'B' or 'W'.
// -repetitions will be between 1 and 3500, inclusive.
// -The total number of balls after generating the sequence will be between 1 and 100000, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// "BBWWB"
// 1
// 
// Returns: 2
// 
// The starting contents of the stack from top to bottom are: BBWWB. The process can be simulated as follows:
// 
// (Stack contents: BBWWB). Take a black ball, change the contents from BWWB to WBBW.
// (Stack contents: WBBW). Take a white ball, change the contents from BBW to WBB.
// (Stack contents: WBB). Take a white ball, change the contents from BB to BB.
// (Stack contents: BB). Take a black ball, change the contents from B to W.
// (Stack contents: W). Take a white ball.
// 
// 
// 
// 1)
// "BBB"
// 10
// 
// Returns: 1
// 
// There are initially 30 black balls in the stack. After the first one is processed, all the remaining balls become white. A white ball cannot change the color of the remaining balls.
// 
// 2)
// "BW"
// 10
// 
// Returns: 20
// 
// A series of alternating black and white balls which begins with a black ball. Initially, a black ball inverts the colors of the remaining balls, making them a new alternation of black and white balls that begins with a black ball. The process will repeat for each ball and each ball will be black when picked.
// 
// 3)
// "WWWWWWWBWWWWWWWWWWWWWW"
// 1
// 
// Returns: 2
// 
// Eventually, the black ball will be reached after reversing the order 14 times. It will turn all of the remaining balls black. But the next black ball that is processed will turn all the remaining balls white once again.
// 
// 
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
