#include <bits/stdc++.h>
using namespace std;

class Paintball
{
public:
	vector <string> getLeaderboard(vector <string> players, vector <string> messages);
};

class Team {
 public:
    string name;
    int score;
    map <string, int> players;
    bool operator <(const Team &ob) const {
        return score != ob.score ? score > ob.score : name < ob.name;
    }
};

bool cmp(const pair<string, int> &pl1, const pair <string, int> &pl2) {
    return pl1.second != pl2.second ? pl1.second > pl2.second : pl1.first < pl2.first;
}

string toString(int n) {
    stringstream ss;
    ss << n;
    return ss.str();
}

vector <string> Paintball::getLeaderboard (vector <string> players, vector <string> messages)
{
	vector <string> ret;
    map <string, Team> info;
    map <string, string> getTeam;

    for(int i =0; i < (int)players.size(); i++){
        stringstream ss(players[i]);
        string tm, pl;
        ss >> pl >> tm;
        info[tm].name = tm;
        info[tm].players[pl] = 0;
        getTeam[pl] = tm;
    }
    for(int i = 0; i < (int)messages.size(); ++i) {
        stringstream ss(messages[i]);
        string pl1, tm, pl2;
        ss >> pl1 >> tm >> pl2;
        string tm1 = getTeam[pl1], tm2 = getTeam[pl2];
        if(tm1 == tm2) {
            info[tm1].score--;
            info[tm1].players[pl1]--;
        }
        else {
            info[tm1].score++;
            info[tm1].players[pl1]++;
            info[tm2].score--;
            info[tm2].players[pl2]--;
        }
    }
    vector <Team> tm;
    for(auto it = (info).begin(); it != (info).end(); ++it) {
        tm.push_back(it->second);
    }
    sort(tm.begin(), tm.end());
    for(int i = 0; i < (int)tm.size(); ++i) {
        ret.push_back(tm[i].name + " " + toString(tm[i].score));
//        cout << tm[i].name << ": " << tm[i].score << "\n";
        vector <pair<string, int> > pl;
        for(auto it = (tm[i].players).begin(); it != (tm[i].players).end(); ++it) {
            pl.push_back(make_pair(it->first, it->second));
        }
        sort(pl.begin(), pl.end(), cmp);
        for(auto it = (pl).begin(); it != (pl).end(); ++it) {
            ret.push_back("  " + it->first + " " + toString(it->second));
//            cout << it->first << " " << it->second << "\n";
        }
//        cout << "\n";
    }
	return ret;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <string> p1, bool hasAnswer, vector <string> p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	Paintball *obj;
	vector <string> answer;
	obj = new Paintball();
	clock_t startTime = clock();
	answer = obj->getLeaderboard(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p2.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << "\"" << p2[i] << "\"";
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << answer[i] << "\"";
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p2.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p2[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	vector <string> p0;
	vector <string> p1;
	vector <string> p2;
	
	// ----- test 0 -----
	disabled = false;
	p0 = {"A RED","B BLUE"};
	p1 = {"A SPLATTERED B"};
	p2 = {"RED 1","  A 1","BLUE -1","  B -1"};
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = {"LISA RED","BART RED","HOMER BLUE","MARGE BLUE","MAGGIE GREEN"};
	p1 = {"MAGGIE SPLATTERED HOMER","MAGGIE SPLATTERED MARGE"};
	p2 = {"GREEN 2","  MAGGIE 2","RED 0","  BART 0","  LISA 0","BLUE -2","  HOMER -1","  MARGE -1"};
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = {"TODD STRIKEFORCE","BART OMEGA","DATA STRIKEFORCE","MILHOUSE OMEGA","NELSON DISCOVERYCHANNEL","MARTIN DISCOVERYCHANNEL"};
	p1 = {"BART SPLATTERED MARTIN","TODD SPLATTERED MARTIN"};
	p2 = {"OMEGA 1","  BART 1","  MILHOUSE 0","STRIKEFORCE 1","  TODD 1","  DATA 0","DISCOVERYCHANNEL -2","  NELSON 0","  MARTIN -2"};
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = {"DR COHO","ST COHO","PE COHO"};
	p1 = {"DR SPLATTERED ST","ST SPLATTERED PE"};
	p2 = {"COHO -2","  PE 0","  DR -1","  ST -1"};
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 4 -----
	disabled = false;
	p0 = {"A B","AA AA","AAA AAA"};
	p1 = {"A SPLATTERED AAA","A SPLATTERED AAA","A SPLATTERED AAA","AA SPLATTERED AAA","AA SPLATTERED AAA"};
	p2 = {"B 3","  A 3","AA 2","  AA 2","AAA -5","  AAA -5"};
	all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// For his birthday, Bart received the brand new video game "Paintball!".  In this game, a person plays on teams over the Internet against various competitors, attempting to hit their opponents with paint balls.  Each player earns a point each time that they "splatter" an opponent with a paintball, and lose a point for each time they get "splattered".  Due to the way that the game is played, it is also possible to accidentally splatter yourself or a teammate.  In that case, the shooter loses a point, and the person who was splattered (if not the shooter) does not lose any points.  A team's score is simply the sum of the scores of its players.
// 
// Although Bart loves the game, he is disappointed that the game does not provide a leaderboard during gameplay.  However, it does provide the list of players, formatted as "NAME TEAM" (where NAME is the player's name, and TEAM is his team), and a series of messages, each formatted as "NAME1 SPLATTERED NAME2" (all quotes for clarity), where NAME1 indicates the name of the person who shot the paintball, and NAME2 indicates the name of the person who got splattered.  Bart would like to have an updated scoreboard, and that is where you come in.
// 
// All teams will receive a rank number from 1 to M (the total number of teams), based on the team scores (with 1 corresponding to the highest score).  If multiple teams have the same score, then the team with the name that comes first alphabetically will receive a lower rank number.  For each team (in order from 1 to M), its leaderboard entry will be formatted as follows:
// 
// The first line will be "TEAM SCORE" (quotes for clarity), where TEAM is the team name, and SCORE is the team score (with no extra leading zeroes).
// Let N be the number of players on the team.  Assign rank numbers to the N players from 1 to N, giving a lower rank number to a higher score.  If multiple players have the same score, assign the player whose name comes first alphabetically to the lower rank number.
// From the player with rank 1 to rank N, output a line with 2 spaces, the player's name, a single space, and then the player's score (with no extra leading zeroes).  
// 
// Thus, if player A from team RED splatters player B from team BLUE (and they are the only players in the game), the leaderboard will be:
// 
// RED 1
//   A 1
// BLUE -1
//   B -1
// 
// You are to generate the leaderboard and return it.
// 
// 
// DEFINITION
// Class:Paintball
// Method:getLeaderboard
// Parameters:vector <string>, vector <string>
// Returns:vector <string>
// Method signature:vector <string> getLeaderboard(vector <string> players, vector <string> messages)
// 
// 
// NOTES
// -A SCORE of 0 should be output as 0, not as -0.
// 
// 
// CONSTRAINTS
// -players will contain between 1 and 50 elements, inclusive.
// -Each element of players will contain between 3 and 50 characters, inclusive.
// -Each element of players will be formatted as "NAME TEAM" (quotes for clarity).
// -In each element of players, NAME will consist of uppercase characters ('A'-'Z') and will contain at least 1 character.
// -There will be no duplicate NAMEs in players.
// -In each element of players, TEAM will consist of uppercase characters ('A'-'Z') and will contain at least 1 character.
// -messages will contain between 1 and 50 elements, inclusive.
// -Each element of messages will contain between 14 and 50 characters, inclusive.
// -Each element of messages will be formatted as described in the problem statement.
// -In each element of messages, NAME1 and NAME2 will be NAMEs found in players.
// 
// 
// EXAMPLES
// 
// 0)
// {"A RED", "B BLUE"}
// {"A SPLATTERED B"}
// 
// Returns: {"RED 1", "  A 1", "BLUE -1", "  B -1" }
// 
// The example from the statement.
// 
// 1)
// {"LISA RED", "BART RED", "HOMER BLUE", "MARGE BLUE", "MAGGIE GREEN"}
// {"MAGGIE SPLATTERED HOMER", "MAGGIE SPLATTERED MARGE"}
// 
// Returns: {"GREEN 2", "  MAGGIE 2", "RED 0", "  BART 0", "  LISA 0", "BLUE -2", "  HOMER -1", "  MARGE -1" }
// 
// 
// 
// 2)
// {"TODD STRIKEFORCE",
//  "BART OMEGA",
//  "DATA STRIKEFORCE",
//  "MILHOUSE OMEGA",
//  "NELSON DISCOVERYCHANNEL",
//  "MARTIN DISCOVERYCHANNEL"}
// {"BART SPLATTERED MARTIN","TODD SPLATTERED MARTIN"}
// 
// Returns: {"OMEGA 1", "  BART 1", "  MILHOUSE 0", "STRIKEFORCE 1", "  TODD 1", "  DATA 0", "DISCOVERYCHANNEL -2", "  NELSON 0", "  MARTIN -2" }
// 
// 
// 
// 3)
// {"DR COHO", "ST COHO", "PE COHO"}
// {"DR SPLATTERED ST",
//  "ST SPLATTERED PE"}
// 
// Returns: {"COHO -2", "  PE 0", "  DR -1", "  ST -1" }
// 
// Don't shoot your teammates!
// 
// 4)
// {"A B", "AA AA", "AAA AAA"}
// {"A SPLATTERED AAA", "A SPLATTERED AAA", "A SPLATTERED AAA", 
// "AA SPLATTERED AAA", "AA SPLATTERED AAA"}
// 
// Returns: {"B 3", "  A 3", "AA 2", "  AA 2", "AAA -5", "  AAA -5" }
// 
// 
// 
// END KAWIGIEDIT TESTING
