#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <climits>
#include <cstring>
using namespace std;

typedef long long  int64;
typedef vector<int> vi;
typedef string ST;
typedef stringstream SS;
typedef vector< vector <int> > vvi;
typedef pair<int,int> ii;
typedef vector <string> vs;

#define Pf	printf
#define	Sf	scanf

#define	ep	1e-9
#define PI M_PI
#define E M_E

#define	CL(a, b)	memset(a, b, sizeof(a))
#define	mp	make_pair

#define	pb	push_back

#define	all(c)	(c).begin(), (c).end()
#define	tr(i, c)	for(typeof((c).begin()) i = (c).begin(); i != (c).end(); i++)

#define	present(x, c)	((c).find(x) != (c).end())		//map & set//
#define	cpresent(x, c)	(find(all(c),x) != (c).end())	//vector & list//

#define forn(i, n)	for(int i = 0, loop_ends_here = (int)n; i < loop_ends_here; i++)
#define forab(i, a, b)	for(int i = a, loop_ends_here = (int) b; i <= loop_ends_here; i++)
#define rep(i, a, b)	for(int i = a, loop_ends_here = (int)b; i>=loop_ends_here; i--)

vi a;

int grundy() {
	set<int> s;
	forn(i, a.size())	if(a[i] > 0) {
		forab(j, i+1, a.size() - 1) {
			forab(k, j, a.size() - 1) {
				a[i]--;	a[j]++;	a[k]++;
				s.insert(grundy());
				a[i]++;	a[j]--;	a[k]--;
			}
		}
	}
	int ret = 0;
	tr(it, s) {
		if(ret != *it)
			break;
		ret++;
	}
	return ret;
}

//const int sz = 2001;
//int GN[sz][sz];

int gn(int x, int y, int z = 0) {
	return (y & 1) ;
/*
	assert(x >= 0 && x < sz && y >= 0 && y < sz);

	int &ret = GN[x][y];

	if(ret > -1)
		return ret;

	if(x + y == 0)
		return ret = 0;

	if(x == 0) 
		return ret = (gn(x, y-1, 0) == 0 ? 1 : 0);
	
	if(y == 0)
		return ret = gn(x-1, y+1, 0) == 0 ? 1 : 0;

	int a = gn(x-1, y+1, 0), b = gn(x, y-1, 0);

	if(a > b)
		swap(a, b);

	if(a == 0)
		return ret = b == 1 ? 2 : 1;

	return ret = 0;
*/
}

class Roxor
{
public:
	vector <int> play(vector <int> piles)
	{
//		CL(GN, -1);
		a = piles;
		int gf = 0;
		int ret = 0;

		forn(i, a.size())	if(a[i] > 0) {
			forab(j, i+1, a.size() - 1) {
				forab(k, j, a.size() - 1) {
					Pf("%d-%d, %d-%d, %d-%d, gn = %d\n", i, a[i], j, a[j], k, a[k], gn(a[i], a[j], a[k]));
//					ret ^= gn(a[i], a[j], a[k]);
				}
			}
		}

		return vi (1, ret);

//		int x, y;
//		while(cin >> x >> y)
//			cout << gn(x, y) << endl;

/*
		vector <int> ret;
		
		forn(i, a.size()) if(a[i] > 0) {
			forab(j, i+1, a.size() - 1) {
				forab(k, j, a.size() - 1) {
					a[i]--;	a[j]++;	a[k]++;
					if(grundy() == 0) {
						ret.pb(i);	ret.pb(j);	ret.pb(k);
						return ret;
					}
				}
			}
		}
		
		return ret;
*/
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, bool hasAnswer, vector <int> p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}";
	cout << "]" << endl;
	Roxor *obj;
	vector <int> answer;
	obj = new Roxor();
	clock_t startTime = clock();
	answer = obj->play(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p1.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << p1[i];
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << answer[i];
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p1.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p1[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <int> p1;
	
	{
	// ----- test 0 -----
	int t0[] = {0,0,1,0,1,100};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,4,5};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {1000,1000,1000,1000,1000};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1.clear() /*{}*/;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {2,1,1,1,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {0,1,1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {14,301,391,410,511,681,58,259,981,81,5,42,251,401,120};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,5,14};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Roxor is a 2-player game that is played with several piles of stones, numbered 0, 1, ..., n-1. To make a move, a player chooses three piles with numbers i, j, and k such that i < j, j <= k, and pile i has at least one stone in it. The player then removes one stone from pile i, and adds one stone to piles j and k. Note that j may equal k, and that two stones are added for each stone removed. Players make moves alternately until it is no longer possible to make a valid move. This will always happen eventually, and the last player to have moved is then declared the winner. See example 0 below for a description of an entire game.
// 
// 
// You are said to have made a "winning move" in Roxor, if after making that move, you can eventually win no matter what the opponent does. Note that a winning move does not necessarily end the game immediately, but if you make only winning moves, you will win eventually.
// 
// 
// For this task, you will be given a vector <int> piles, representing the number of stones in each pile within a game of Roxor. You must find i, j, k with i < j and j <= k such that removing one stone from pile i and adding one stone to piles j and k is a winning move. If there are multiple winning moves, you should choose one that minimizes i. If there is more than one of these, you should choose one that minimizes j. If there is still a tie, choose the one that minimizes k. 
// 
// 
// If there is at least one winning move, you should return {i, j, k} as described above. Otherwise, return {}.
// 
// 
// DEFINITION
// Class:Roxor
// Method:play
// Parameters:vector <int>
// Returns:vector <int>
// Method signature:vector <int> play(vector <int> piles)
// 
// 
// CONSTRAINTS
// -piles will contain between 2 and 15 elements inclusive.
// -Each element of piles will be between 0 and 1000 inclusive.
// -At least one element of piles other than the last element will be larger than 0.
// 
// 
// EXAMPLES
// 
// 0)
// {0, 0, 1, 0, 1, 100}
// 
// Returns: { 2,  4,  5 }
// 
// You have 7 legal moves in this position:
// {2, 3, 3}, {2, 3, 4}, {2, 3, 5}, {2, 4, 4}, {2, 4, 5}, {2, 5, 5}, and {4, 5, 5}.
// 
// If you make the move, {2, 4, 5}, the piles become {0, 0, 0, 0, 2, 101}.
// Your opponent then has to make the move, {4, 5, 5}, which makes the piles become {0, 0, 0, 0, 1, 103}.
// Finally, you can make the move, {4, 5, 5}, so the piles become {0, 0, 0, 0, 0, 105}.
// Your opponent now has no legal moves, so you have won. Thus, {2, 4, 5} is a winning move.
// 
// 1)
// {1000, 1000, 1000, 1000, 1000}
// 
// Returns: { }
// 
// Your opponent can always beat you from this position by simply copying your moves. This will ensure that there is always an even number of stones in each pile at the beginning of your turn. As such, you will never take the last stone from any pile, and therefore, you cannot win.
// 
// 2)
// {2, 1, 1, 1, 5}
// 
// Returns: { 0,  1,  1 }
// 
// 3)
// {14, 301, 391, 410, 511, 681, 58, 259, 981, 81, 5, 42, 251, 401, 120}
// 
// Returns: { 2,  5,  14 }
// 
// END KAWIGIEDIT TESTING




//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
